Repository gianfrancodumoulinbertucci/SOEN341, pull requests merged in 2021-03, with the labels that each got.

#45 Feat/user account page
  .gitignore
  app/__pycache__/forms.cpython-37.pyc
  app/app.py
  app/static/images/Avatar.png
  app/static/images/Heads_Image.jpg
  app/static/images/b21.png
  app/static/images/central-america-maps.png
  app/static/images/images copy 2.jpeg
  app/static/main.css
  app/static/posts.json
  app/templates/account.html
  app/templates/layout.html
Labels: feature

#47 testing language used
  .travis.yml
  conftest.py
  test_lang.py
Labels: Priority: Urgent, test

#48 Feat/as a user i want to follow people
  app/app.py
  app/forms.py
  app/static/accounts.json
  app/static/main.css
  app/templates/account.html
  app/templates/timeline.html
Labels: 0 pts, PR, Priority: Urgent
